const data = [
  {
    id: 1,
    src: './property/1.jpg',
    title: 'Two Bedroom Flat',
    offer: 'For Sale',
    state: 'Rivers',
    country: 'Nigeria',
    price: 20000,
  },
  {
    id: 2,
    src: './property/2.jpg',
    title: 'Two Bedroom Flat',
    offer: 'For Rent',
    state: 'Cross Rivers',
    country: 'Nigeria',
    price: 30000,
  },
  {
    id: 3,
    src: './property/3.jpeg',
    title: 'Bungalow',
    offer: 'For Sale',
    state: 'Lagos',
    country: 'Nigeria',
    price: 5000,
  },
  {
    id: 4,
    src: './property/5.jpg',
    title: 'Self Contain',
    offer: 'For Sale',
    state: 'Abuja',
    country: 'Nigeria',
    price: 40000,
  },
  {
    id: 5,
    src: './property/7.jpg',
    title: 'Two Bedroom Flat',
    offer: 'For Rent',
    state: 'Abia',
    country: 'Nigeria',
    price: 8000,
  },
  {
    id: 6,
    src: './property/8.jpg',
    title: 'Flat',
    offer: 'For Sale',
    state: 'Lagos',
    country: 'Nigeria',
    price: 6500,
  },
]
export default data
